### ISSUE TITLE
Metadata proposal

### ISSUE THREAD

**Issue by stuartlynn** [Urban-Analytics-Technology-Platform/poppusher#34]
Thinking about the output for popgetter, we need to define a consistent way to refer to given metrics a user might want to access. After chat in the office last week, we talked about having a code and expansion type system where there is a core set of fields that all sources produce and then a series of custom ones that might vary from source to source.  This is a proposal for the metadata 

### Core metadata which is available for all resources

- **human_readable_name** _String_: A human readable name for the metric, something like "Total Population under 12 years old"
- **metric_name** _String_: The name of the metric that comes from the source dataset ( for example in the ACS this might be "B001_E001" or something similar)
- **description** _String_: A longer description of the metric which might include info on the caveats for the metric
- **metric_file** _String_  : The location (URL) of the parquet file that contains this metric value 
- **column_name**  _String_ : The name of column in the outputted parquet file which contains the metric
- **geometry_level** _String_: The name of the geometry level at which this metric was captured (in the US this could be tracts or block groups, in the UK output areas etc)
- **country** _String_: The three letter country code for the country that this metric was gathered from
- **data_product** _String_: The data product that the metric was taken from "ACS_1year" etc 
- **date_valid_from** _Date_: The date that the metric starts being relevant
- **date_valid_to** _Date_: The date that the metric stops being relevant
- **margin_of_error_column** _String_:  Name of the column if any that contains the margin of error for the metric 
- **margin_of_error_file** _String_: Location (url) of the parquet file that contains the margin of error for the metric
- **potential_denominators** _Array<String>_:  a list of metrics which are suitable denominators for this metric.
- **parent_metric** _String_ :  The metric if any which is the parent to this one ( some census data like the ACS is organised hierarchically, this can be useful for making the metadata more searchable)
The extended metadata then contains any additional details about the metric which might be country specific.

**Comment by dabreegster** [comment]
To check my understanding, these would be filled out per country and per common metric (like "Total Population under 12 years old")? At first glance, it looks like lots of metadata about a single column, but it makes sense, since there won't be tons of of these. All the same, would it be useful at all to organize this list into fields specific to that one column, and those more generally for the per-country dataset? Something like:

dataset-wide: metric_file, geometry_level, country, data_product, date_valid_from, date_valid_to, 
just the one metric: human_readable_name, metric_name, description, column_name, potential_denominators, parent_metric
(not sure about the margin of error fields)

Edit: maybe a parquet file has the dataset-wide metadata logically attached to it, and the metric can then point to all of that?

**Comment by stuartlynn** [comment]
Yeah this would be one per metric, which would be some value that represents a population within a country. There would be one per [metric, year, geometry_level] tuple.

There might be more of these than you expect. For example there are a few thousand of these in the American Community survey that break down the population in different ways.

I think we can split some of these into dataset / metric groups, with a reference to the dataset metadata entry in the metric details. 

Just a note that metric_file probably needs to be at the metric level as we might want to split the metrics from the same survey in to different files for performance reasons.

**Comment by andrewphilipsmith** [comment]
Thanks for this, Stuart. It's great to see this written down.

Below are my initial thoughts at the moment - not that I’ve been able to offer answers to some of the questions I’ve raised:

## Unique identifier

Is there a unique identifier for a column/variable? I’m guessing something like this?

```
(country, year, geometry_level, metric_name)
```

Even then, I’m not sure that this would be specific enough. For example, “car_ownship_by_OA” is available from both Census (decadal) and DVLA (yearly). It might be that we can make the metric_name specific enough to distinguish these cases, but that doesn’t feel elegant. It might be worth thinking through the edge cases and actually how prevalent they are. 

## Geographic join

I think we might need to be able to represent more complex geographies than can be achieved with just the `geometry_level`. 

I’d suggest renaming `geometry_level` ⇒ `geometry_file`. This would cover at least two scenarios:

- There might be different, overlapping geography hierarchies, eg census, admin, health, postcodes etc (see here for an example https://open-innovations.org/data/geographies), etc with different taxonomies for their levels.
- It would also allow for boundary changes between years (e.g. link to the separate files for the 2011 boundaries or the 2021 boundaries).

However, this still doesn’t fully deal with the scenario of a devolved census (see below).

## Null metadata

I don’t know if this is intended or not, but it feels that some of those metadata values ought to allow null values: 

- date_valid_to
- margin_of_error_column
- margin_of_error_file
- potential_denominators
- parent_metric

(Philosophically, does this mean that they are still “core” metadata? 😉 )

## Metric_name

The `metric_name` is where HXL would be ideal and saves us a lot of re-inventing.

## Devolved censuses

In some countries, the census is devolved to a federal subdivision, meaning that the variables collected and their names are not consistent across the country. (The UK is one such example). I’m not quite sure how we would represent this within this metadata. For the UK, we have; “Super Output Areas, Lower Layer” (England and Wales), “Super Output Areas” (Northern Ireland) and “Data Zones” (Scotland), which all seem to be equivalent despite the different names. Many of the census variables are directly comparable across the UK, though some notable exceptions exist. We could also create some UK-wide names for comparable geometries.

I think there might be value in something like a `compariable_variables` Array field, but I’ve not properly thought through how that would work (eg could it also indicate comparable variables from other census years, or non-census sources?)

**Comment by stuartlynn** [comment]
@andrewphilipsmith Awesome thanks.

> Thanks for this, Stuart. It's great to see this written down.
> 
> Below are my initial thoughts at the moment - not that I’ve been able to offer answers to some of the questions I’ve raised:
> 
> ## Unique identifier
> Is there a unique identifier for a column/variable? I’m guessing something like this?
> 
> ```
> (country, year, geometry_level, metric_name)
> ```
> 

Yeah that tupple with the addition of ```data_product``` would uniquely identify the metric in the metadata. This will enable the case you mention with car ownership.

> Even then, I’m not sure that this would be specific enough. For example, “car_ownship_by_OA” is available from both Census (decadal) and DVLA (yearly). It might be that we can make the metric_name specific enough to distinguish these cases, but that doesn’t feel elegant. It might be worth thinking through the edge cases and actually how prevalent they are.
> 
> ## Geographic join
> I think we might need to be able to represent more complex geographies than can be achieved with just the `geometry_level`.
> 
> I’d suggest renaming `geometry_level` ⇒ `geometry_file`. This would cover at least two scenarios:
> 
> * There might be different, overlapping geography hierarchies, eg census, admin, health, postcodes etc (see here for an example https://open-innovations.org/data/geographies), etc with different taxonomies for their levels.
> * It would also allow for boundary changes between years (e.g. link to the separate files for the 2011 boundaries or the 2021 boundaries).
> 
I think we want both right?  I want to be able to find all metrics that are defined at the census tract level in the years 2020-2023 for example. So I want to query the geometry level and then be able to construct the geometry file url from the combination of the year and the geometry level. I was imagining that happening through convention in the code but we could include an explicit ```geometry_file_url``` instead

> However, this still doesn’t fully deal with the scenario of a devolved census (see below).
> 
> ## Null metadata
> I don’t know if this is intended or not, but it feels that some of those metadata values ought to allow null values:
> 
> * date_valid_to
> * margin_of_error_column
> * margin_of_error_file
> * potential_denominators
> * parent_metric
> 
> (Philosophically, does this mean that they are still “core” metadata? 😉 )

I was going back and forth on adding if a variable was optional or not in this first pass but your right not all of these will be needed /  available for every source. I think they are still core metadata in that, for example.  I want to understand for every metric if it has an error estimate or not.

This might just be my indoctrination by Rust but I think using null values in something like this is too blunt a tool. It would be great to have something a little more expressive like "missing" / "unavailable" / "non applicable".

> 
> ## Metric_name
> The `metric_name` is where HXL would be ideal and saves us a lot of re-inventing.
> 
Yeah for sure lets add a HXL field to this. I am torn a little between having that as the unique identifier or as an additional required field. Need to look at the HXL naming conventions more. 
> ## Devolved censuses
> In some countries, the census is devolved to a federal subdivision, meaning that the variables collected and their names are not consistent across the country. (The UK is one such example). I’m not quite sure how we would represent this within this metadata. For the UK, we have; “Super Output Areas, Lower Layer” (England and Wales), “Super Output Areas” (Northern Ireland) and “Data Zones” (Scotland), which all seem to be equivalent despite the different names. Many of the census variables are directly comparable across the UK, though some notable exceptions exist. We could also create some UK-wide names for comparable geometries.
> 

That's an interesting use case for sure that I think requires a lot more thought. An initial approach would be just to have them defined at the country level but with a note in the description that defines where in the variable is valid / invalid. 

We could potentially  add a meta data column which indicates within a country level census where a given metric is valid. For example a list of parent administrative level ids or a series of bounding boxes ?

> I think there might be value in something like a `compariable_variables` Array field, but I’ve not properly thought through how that would work (eg could it also indicate comparable variables from other census years, or non-census sources?)

Yeah I like this. It might be a good starting point for the harmonization work too, simply linking to comparable variables.

**Comment by andrewphilipsmith** [comment]
Cutting out a lot of the quotes, to save on having a million indents.....

> Yeah that tupple with the addition of `data_product` would uniquely identify the metric in the metadata. This will enable the case you mention with car ownership.

Agreed. We might need to maintain a list of valid `data_product` values, but I would not add that until we know that we need it.

> I was going back and forth on adding if a variable was optional or not in this first pass but your right not all of these will be needed / available for every source. I think they are still core metadata in that, for example. I want to understand for every metric if it has an error estimate or not.
> 
> This might just be my indoctrination by Rust but I think using null values in something like this is too blunt a tool. It would be great to have something a little more expressive like "missing" / "unavailable" / "non applicable".

Agree - explicitly stating "missing" or "unknown" is better than an ambiguous `null`.

> 
> > ## Metric_name
> > The `metric_name` is where HXL would be ideal and saves us a lot of re-inventing.
> 
> Yeah for sure lets add a HXL field to this. I am torn a little between having that as the unique identifier or as an additional required field. Need to look at the HXL naming conventions more.

I'd suggest trying to use HXL for now. If/when we come up against too many cases that cannot be expressed in HXL, then I think that adding an additional field at that point would not be too hard.


@stuartlynn I think we have enough agreement here to have a try at implementing something. I'm happy to try, but if you have more details thoughts that you'd like to try and implement yourself, there are plenty of other tasks I can busy myself with...

**Comment by andrewphilipsmith** [comment]
Closed by #45 and further refined by #81 and #82.
