### ISSUE TITLE
Create lock for versions for install

### ISSUE THREAD

**Issue by sgreenbury** [Urban-Analytics-Technology-Platform/poppusher#61]
Current install instructions have many pip dependency resolutions and does not complete.

**Comment by sgreenbury** [comment]
Running with Python 3.11 seems to fix this.

**Comment by andrewphilipsmith** [comment]
Referring back to [the hackathon notes](https://hackmd.io/mUIV6OKvRCi_i8h3rDeV9A?view#Debugging-install)

There is already a constraint on the python version in pyproject.toml (introduced [here](https://github.com/Urban-Analytics-Technology-Platform/popgetter/commit/add27cfe972859fac8036fe2ebf7176ca110b31d)):

```
requires-python = ">=3.11,<3.12"
```

What seems odd to me is that `pip` didn't detect this and fail quickly.

**Comment by andrewphilipsmith** [comment]
Oh - though, I've just read that it's generally bad form to put an upper pin on `requires-python`. See https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special
