### ISSUE TITLE
Generating IDs for metadata structs

### ISSUE THREAD

**Issue by yongrenjie** [Urban-Analytics-Technology-Platform/poppusher#83]
## Context

In Wednesday's meeting we resolved to use a normalised, non-nested schema to represent the metadata.

This means that each struct needs to have a unique string to use as an ID. This string should be constructed from a set of fields which uniquely identify it.

This issue is to let us decide:
 - which fields uniquely identify each struct
 - how they should be combined

My proposals are as follows:

----------------------------

### `CountryMetadata`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L9-L17

**Suggestion**

Add `iso3166_2` field (this is required for e.g. Scotland and is included as part of #58)

Use `iso3166_2` as the identifier if present. If `iso3166_2` is None, then use `iso3`

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/867b764e963ff4768d8f6daac9d88346f2a32eae/python/popgetter/metadata.py#L9-L14

-----------------------------

### `DataPublisher`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L20-L28

**Suggestion**

Use `name` as the identifier

-----------------------------

### `SourceDataRelease`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L31-L63

**Suggestion**

In the meeting we said that these should be identified by a tuple of (name, geographic level, year). I've implemented this as a PR in #81:

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/44e5a4d53b0478d20268bdb7d0cf40ae5fb6e21e/python/popgetter/metadata.py#L33-L40

-----------------------------

### `MetricMetadata`

**Current definition**

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/e13d729926e9a37364a9a9147cf5adf0730c91ed/python/popgetter/metadata.py#L66-L112

**Suggestion**

I think this one is the one I'm least certain about. Right now, in #81 I've opted to combine the `source_data_release_id` (which would in turn contain the three fields above) and the HXL tag.

https://github.com/Urban-Analytics-Technology-Platform/popgetter/blob/44e5a4d53b0478d20268bdb7d0cf40ae5fb6e21e/python/popgetter/metadata.py#L69-L77

In place of the HXL tag, I could equally see us using either:
 - the human-readable name (problem: this might end up being really quite long)
 - the parquet column name (problem: this might not be unique if there are multiple parquet files belonging to the same source data release)

Which of these is the best?

**Comment by sgreenbury** [comment]
Thanks for this @yongrenjie, a few comments/thoughts:
- `CountryMetadata`: I think your suggestion works well and covers a mixture of cases where `iso3116_2` may or may not be present.
- `DataPublisher` and `SourceDataRelease`: I think your suggestions sound good. Using lower case for name (and in general) sounds like a good option so there is no uncertainty for a given char whether it is capitalized. What do we think about the presence of non-alphanumeric characters - would this be an issue? An example Scotland `SourceDataRelease` is: `Census 2011: Release 2A` which would become `census 2011: release 2a` and this includes both ` ` and `:`, perhaps it would be worth including additional transformations of these chars into a single separator e.g. `_` to simplify this further? However, not all chars may be best transformed to `_` (e.g. `'` in cases such as `'s`). Would HXL provide guidance on this?
- `MetricMetadata`: I think your suggestion of HXL tag is a good option as it should be more succinct than human-readable name (as you mention), universal across releases and unique per release.

One other thought that could help guide this -- are we expecting to make the IDs available to users?

**Comment by yongrenjie** [comment]
@sgreenbury That's a good point, yeah — my inclination is that the IDs should consist only of `[A-Za-z0-9_]` and thus lowercase -> split on non-alphanumeric -> join with `_` would be fine here.

The other broad option I considered would be to create a hash from the string(s). I do think this might be cleaner (you wouldn't end up with unusually long strings), and people are used to hashes already (git commits?). It's not human readable but if people want the human readable info they can query the other fields.

I think that IDs should be exposed to users. Maybe getting ahead of ourselves here, but for example let's say someone wants to query all `SourceDataRelease`s including the word 'census'. This would return a list, like

     release_id       name              other   fields   ...
     -------------    ----------------  -----   ------   ---
     abcde            ons census 2011   ...     ...      ...
     ghijk            ons census 2021   ...     ...      ...
     ...              ...               ...     ...      ...


And then if the user wants to find all metadata associated with the 2011 census, they'd then run something like

     popgetter list-datasets --release-id abcde

In this respect maybe it's easier to fix IDs to a certain length (6 or 7 chars) - otherwise we might end up with rather long IDs — and the best way to do that would almost certainly be a hash.

The other way I see IDs being used is something which Stuart said: the user provides a YAML file (or other format) of datasets they want, which would involve specifying the IDs, and then popgetter downloads all of it for them.

**Comment by yongrenjie** [comment]
Current plan based on @sgreenbury's idea is to generate JSON from all the other fields of the class, canonicalise the JSON (using [RFC 8785](https://datatracker.ietf.org/doc/html/rfc8785)), and then generate a SHA256 hash from that.

Much like git commit hashes, the CLI should only show the user the first 5 or 6 characters of the hash, and the user should be able to specify metadata using shortened hashes. The full hash can be shown upon request but should only really be needed in the very unlikely event of collision.

This is implemented in #82
